name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}  # Accessing API key from GitHub Secrets
jobs:
  build:

    runs-on: ubuntu-latest
    environment: master
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true  # Ensures a clean checkout
        submodules: false  # Disables submodule fetching

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci --force
 # Build the application with environment variables
    - name: Build React App
      run: CI=false npm run build --if-present
    
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}