name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true  # Ensures a clean checkout
        submodules: false  # Disables submodule fetching

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci --force

    # Update browserslist database
    - name: Update Browserslist DB
      run: npx update-browserslist-db@latest

    # Build the project with CI set to false to avoid treating warnings as errors
    - run: CI=false npm run build --if-present

    # Run tests
    - run: npm test
    
    # Deploy with gh-pages
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
